services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: bot
    depends_on:
      - postgres
    # Get environment variables from .env file
    env_file:
      - path: ./.env
    volumes:
      - .:/app
    # command: ["./bin/bot"]
    # For development we just run air
    command: ["air", "-c", ".air-bot.toml"]
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web
    depends_on:
      - bot
    env_file:
      - path: ./.env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    # command: ["./bin/web"]
    # For development we just run air
    command: ["air"]
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
